/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as LangDownloadRouteImport } from './routes/$lang/download'
import { Route as LangDocsSplatRouteImport } from './routes/$lang/docs/$'
import { Route as LangDevSplatRouteImport } from './routes/$lang/dev/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/$lang/',
  path: '/$lang/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LangDownloadRoute = LangDownloadRouteImport.update({
  id: '/$lang/download',
  path: '/$lang/download',
  getParentRoute: () => rootRouteImport,
} as any)
const LangDocsSplatRoute = LangDocsSplatRouteImport.update({
  id: '/$lang/docs/$',
  path: '/$lang/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LangDevSplatRoute = LangDevSplatRouteImport.update({
  id: '/$lang/dev/$',
  path: '/$lang/dev/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang/download': typeof LangDownloadRoute
  '/api/search': typeof ApiSearchRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/dev/$': typeof LangDevSplatRoute
  '/$lang/docs/$': typeof LangDocsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/download': typeof LangDownloadRoute
  '/api/search': typeof ApiSearchRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/dev/$': typeof LangDevSplatRoute
  '/$lang/docs/$': typeof LangDocsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang/download': typeof LangDownloadRoute
  '/api/search': typeof ApiSearchRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/dev/$': typeof LangDevSplatRoute
  '/$lang/docs/$': typeof LangDocsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang/download'
    | '/api/search'
    | '/$lang/'
    | '/$lang/dev/$'
    | '/$lang/docs/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/download'
    | '/api/search'
    | '/$lang'
    | '/$lang/dev/$'
    | '/$lang/docs/$'
  id:
    | '__root__'
    | '/'
    | '/$lang/download'
    | '/api/search'
    | '/$lang/'
    | '/$lang/dev/$'
    | '/$lang/docs/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangDownloadRoute: typeof LangDownloadRoute
  ApiSearchRoute: typeof ApiSearchRoute
  LangIndexRoute: typeof LangIndexRoute
  LangDevSplatRoute: typeof LangDevSplatRoute
  LangDocsSplatRoute: typeof LangDocsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/$lang'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/download': {
      id: '/$lang/download'
      path: '/$lang/download'
      fullPath: '/$lang/download'
      preLoaderRoute: typeof LangDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/docs/$': {
      id: '/$lang/docs/$'
      path: '/$lang/docs/$'
      fullPath: '/$lang/docs/$'
      preLoaderRoute: typeof LangDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/dev/$': {
      id: '/$lang/dev/$'
      path: '/$lang/dev/$'
      fullPath: '/$lang/dev/$'
      preLoaderRoute: typeof LangDevSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangDownloadRoute: LangDownloadRoute,
  ApiSearchRoute: ApiSearchRoute,
  LangIndexRoute: LangIndexRoute,
  LangDevSplatRoute: LangDevSplatRoute,
  LangDocsSplatRoute: LangDocsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
