/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as LangTeamRouteImport } from './routes/$lang/team'
import { Route as LangSponsorshipRouteImport } from './routes/$lang/sponsorship'
import { Route as LangNewsRouteImport } from './routes/$lang/news'
import { Route as LangMembershipRouteImport } from './routes/$lang/membership'
import { Route as LangLicenseRouteImport } from './routes/$lang/license'
import { Route as LangLegalRouteImport } from './routes/$lang/legal'
import { Route as LangDownloadRouteImport } from './routes/$lang/download'
import { Route as LangDonateRouteImport } from './routes/$lang/donate'
import { Route as LangContactUsRouteImport } from './routes/$lang/contact-us'
import { Route as LangDocsSplatRouteImport } from './routes/$lang/docs/$'
import { Route as LangDevSplatRouteImport } from './routes/$lang/dev/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/$lang/',
  path: '/$lang/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LangTeamRoute = LangTeamRouteImport.update({
  id: '/$lang/team',
  path: '/$lang/team',
  getParentRoute: () => rootRouteImport,
} as any)
const LangSponsorshipRoute = LangSponsorshipRouteImport.update({
  id: '/$lang/sponsorship',
  path: '/$lang/sponsorship',
  getParentRoute: () => rootRouteImport,
} as any)
const LangNewsRoute = LangNewsRouteImport.update({
  id: '/$lang/news',
  path: '/$lang/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LangMembershipRoute = LangMembershipRouteImport.update({
  id: '/$lang/membership',
  path: '/$lang/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const LangLicenseRoute = LangLicenseRouteImport.update({
  id: '/$lang/license',
  path: '/$lang/license',
  getParentRoute: () => rootRouteImport,
} as any)
const LangLegalRoute = LangLegalRouteImport.update({
  id: '/$lang/legal',
  path: '/$lang/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LangDownloadRoute = LangDownloadRouteImport.update({
  id: '/$lang/download',
  path: '/$lang/download',
  getParentRoute: () => rootRouteImport,
} as any)
const LangDonateRoute = LangDonateRouteImport.update({
  id: '/$lang/donate',
  path: '/$lang/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const LangContactUsRoute = LangContactUsRouteImport.update({
  id: '/$lang/contact-us',
  path: '/$lang/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const LangDocsSplatRoute = LangDocsSplatRouteImport.update({
  id: '/$lang/docs/$',
  path: '/$lang/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LangDevSplatRoute = LangDevSplatRouteImport.update({
  id: '/$lang/dev/$',
  path: '/$lang/dev/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang/contact-us': typeof LangContactUsRoute
  '/$lang/donate': typeof LangDonateRoute
  '/$lang/download': typeof LangDownloadRoute
  '/$lang/legal': typeof LangLegalRoute
  '/$lang/license': typeof LangLicenseRoute
  '/$lang/membership': typeof LangMembershipRoute
  '/$lang/news': typeof LangNewsRoute
  '/$lang/sponsorship': typeof LangSponsorshipRoute
  '/$lang/team': typeof LangTeamRoute
  '/api/search': typeof ApiSearchRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/dev/$': typeof LangDevSplatRoute
  '/$lang/docs/$': typeof LangDocsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/contact-us': typeof LangContactUsRoute
  '/$lang/donate': typeof LangDonateRoute
  '/$lang/download': typeof LangDownloadRoute
  '/$lang/legal': typeof LangLegalRoute
  '/$lang/license': typeof LangLicenseRoute
  '/$lang/membership': typeof LangMembershipRoute
  '/$lang/news': typeof LangNewsRoute
  '/$lang/sponsorship': typeof LangSponsorshipRoute
  '/$lang/team': typeof LangTeamRoute
  '/api/search': typeof ApiSearchRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/dev/$': typeof LangDevSplatRoute
  '/$lang/docs/$': typeof LangDocsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang/contact-us': typeof LangContactUsRoute
  '/$lang/donate': typeof LangDonateRoute
  '/$lang/download': typeof LangDownloadRoute
  '/$lang/legal': typeof LangLegalRoute
  '/$lang/license': typeof LangLicenseRoute
  '/$lang/membership': typeof LangMembershipRoute
  '/$lang/news': typeof LangNewsRoute
  '/$lang/sponsorship': typeof LangSponsorshipRoute
  '/$lang/team': typeof LangTeamRoute
  '/api/search': typeof ApiSearchRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/dev/$': typeof LangDevSplatRoute
  '/$lang/docs/$': typeof LangDocsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang/contact-us'
    | '/$lang/donate'
    | '/$lang/download'
    | '/$lang/legal'
    | '/$lang/license'
    | '/$lang/membership'
    | '/$lang/news'
    | '/$lang/sponsorship'
    | '/$lang/team'
    | '/api/search'
    | '/$lang/'
    | '/$lang/dev/$'
    | '/$lang/docs/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/contact-us'
    | '/$lang/donate'
    | '/$lang/download'
    | '/$lang/legal'
    | '/$lang/license'
    | '/$lang/membership'
    | '/$lang/news'
    | '/$lang/sponsorship'
    | '/$lang/team'
    | '/api/search'
    | '/$lang'
    | '/$lang/dev/$'
    | '/$lang/docs/$'
  id:
    | '__root__'
    | '/'
    | '/$lang/contact-us'
    | '/$lang/donate'
    | '/$lang/download'
    | '/$lang/legal'
    | '/$lang/license'
    | '/$lang/membership'
    | '/$lang/news'
    | '/$lang/sponsorship'
    | '/$lang/team'
    | '/api/search'
    | '/$lang/'
    | '/$lang/dev/$'
    | '/$lang/docs/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangContactUsRoute: typeof LangContactUsRoute
  LangDonateRoute: typeof LangDonateRoute
  LangDownloadRoute: typeof LangDownloadRoute
  LangLegalRoute: typeof LangLegalRoute
  LangLicenseRoute: typeof LangLicenseRoute
  LangMembershipRoute: typeof LangMembershipRoute
  LangNewsRoute: typeof LangNewsRoute
  LangSponsorshipRoute: typeof LangSponsorshipRoute
  LangTeamRoute: typeof LangTeamRoute
  ApiSearchRoute: typeof ApiSearchRoute
  LangIndexRoute: typeof LangIndexRoute
  LangDevSplatRoute: typeof LangDevSplatRoute
  LangDocsSplatRoute: typeof LangDocsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/$lang'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/team': {
      id: '/$lang/team'
      path: '/$lang/team'
      fullPath: '/$lang/team'
      preLoaderRoute: typeof LangTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/sponsorship': {
      id: '/$lang/sponsorship'
      path: '/$lang/sponsorship'
      fullPath: '/$lang/sponsorship'
      preLoaderRoute: typeof LangSponsorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/news': {
      id: '/$lang/news'
      path: '/$lang/news'
      fullPath: '/$lang/news'
      preLoaderRoute: typeof LangNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/membership': {
      id: '/$lang/membership'
      path: '/$lang/membership'
      fullPath: '/$lang/membership'
      preLoaderRoute: typeof LangMembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/license': {
      id: '/$lang/license'
      path: '/$lang/license'
      fullPath: '/$lang/license'
      preLoaderRoute: typeof LangLicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/legal': {
      id: '/$lang/legal'
      path: '/$lang/legal'
      fullPath: '/$lang/legal'
      preLoaderRoute: typeof LangLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/download': {
      id: '/$lang/download'
      path: '/$lang/download'
      fullPath: '/$lang/download'
      preLoaderRoute: typeof LangDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/donate': {
      id: '/$lang/donate'
      path: '/$lang/donate'
      fullPath: '/$lang/donate'
      preLoaderRoute: typeof LangDonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/contact-us': {
      id: '/$lang/contact-us'
      path: '/$lang/contact-us'
      fullPath: '/$lang/contact-us'
      preLoaderRoute: typeof LangContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/docs/$': {
      id: '/$lang/docs/$'
      path: '/$lang/docs/$'
      fullPath: '/$lang/docs/$'
      preLoaderRoute: typeof LangDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/dev/$': {
      id: '/$lang/dev/$'
      path: '/$lang/dev/$'
      fullPath: '/$lang/dev/$'
      preLoaderRoute: typeof LangDevSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangContactUsRoute: LangContactUsRoute,
  LangDonateRoute: LangDonateRoute,
  LangDownloadRoute: LangDownloadRoute,
  LangLegalRoute: LangLegalRoute,
  LangLicenseRoute: LangLicenseRoute,
  LangMembershipRoute: LangMembershipRoute,
  LangNewsRoute: LangNewsRoute,
  LangSponsorshipRoute: LangSponsorshipRoute,
  LangTeamRoute: LangTeamRoute,
  ApiSearchRoute: ApiSearchRoute,
  LangIndexRoute: LangIndexRoute,
  LangDevSplatRoute: LangDevSplatRoute,
  LangDocsSplatRoute: LangDocsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
